### ISSUE TITLE
Spelling 

### ISSUE THREAD

**Issue by Rishabh04-02** [lokeshh/samskrit_tools#1]
संस्कृत: Sanskrit or Saṃskṛta

But the latter would just confuse people.

# [reference](https://en.wikipedia.org/wiki/Sanskrit)

**Comment by lokeshh** [comment]
Yes the more popular word is Sanskrit, but the correct one to use should be Samskrit. See [this article](https://www.telegraphindia.com/india/stop-aping-the-sahibs-samskrit-is-how-you-spell-it/cid/1513559). Slowly, more people are adopting it. For example [Samskrit Bharti](https://samskritabharati.in/).

**Comment by Rishabh04-02** [comment]
The British spelling it wrong might be the reason. As NCERT and CBSE still spell it as Sanskrit in their books and syllabus.

**Comment by lokeshh** [comment]
Made the requested changes. I couldn't find the repo myself because I was searching with "Sanskrit" haha
